"use strict"

// create JQUERY object skeletons

var $slide = $('<div>')
  .css('display', 'inline-block')
  .css('border', '2px solid white')
var $image = $('<div>')
  .css('background-size', 'cover')
  .css('width', '300px')
  .css('height', '150px')
  .css('vertical-align', 'top')
  .append('<span class="delete">X</span>')
var $arrows = $('<div>')
  .addClass('arrowsContainer')
  .css('text-align', 'center')
  .append('<i class="back arrow fa fa-arrow-circle-o-left"></i>')
  .append('&nbsp;&nbsp;&nbsp;')
  .append('<i class="forward arrow fa fa-arrow-circle-o-right"></i>')
var $linkUrlInput = $('<input>')
  .attr('type', 'text')
  .addClass('linkUrlInput')
  .css('width', '60%')
  .css('display', 'inline-block')
var $linkUrlButton = $('<button>')
  .css('width', '35%')
  .css('padding', '10px')
  .css('float', 'right')
  .html('update')
var $linkUrlForm = $('<form>')
  .addClass('linkUrlForm')
