requirejs(["../scripts/helper/dropdown.js"])
requirejs(["../scripts/helper/nav.js"])
requirejs(["../scripts/helper/catalog.js"])
requirejs(["../scripts/helper/collection.js"])
requirejs(["../scripts/helper/quickshop.js"])
requirejs(["../scripts/helper/api_calls.js"])
